# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-21 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_delete_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-reorder'], 'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.AlterField(
            model_name='product',
            name='classes',
            field=models.ManyToManyField(related_name='classes', to='mall.Classify', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='%Y%m/product', verbose_name='主图'),
        ),
    ]
