# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-22 07:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20200421_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classify',
            options={'verbose_name': '商品分类', 'verbose_name_plural': '商品分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '商品标签', 'verbose_name_plural': '商品标签'},
        ),
        migrations.AddField(
            model_name='classify',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mall.Classify'),
        ),
        migrations.AlterField(
            model_name='product',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='classes', to='mall.Classify', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='mall.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='商品id'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='tags', verbose_name='主图'),
        ),
    ]
