# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-17 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200413_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='关联的id'),
        ),
    ]
